### PR TITLE
Fix gem2s in testthat

### PR DESCRIPTION
**Pull request by ogibson**
# Description

# Details
#### URL to issue
N/A

#### Link to staging deployment URL (or set N/A)
N/A

#### Integration test branch
master

# Merge checklist
Your changes will be ready for merging after all of the steps below have been completed.

### Code updates
Have best practices and ongoing refactors being observed in this PR
- [ ] Migrated any selector / reducer used to the new format.

### Manual/unit testing
- [X] Tested changes using InfraMock locally **or** no tests required for change, e.g. Kubernetes chart updates.
- [ ] Validated that current unit tests for code work as expected and are sufficient for code coverage **or** no unit tests required for change, e.g. documentation update.
- [ ] Unit tests written **or** no unit tests required for change, e.g. documentation update.

### Integration testing
**You must check the box below** to run integration tests on the latest commit on your PR branch.
Integration tests have to pass before the PR can be merged. Without checking the box, your PR
**will not pass** the required status checks for merging.

- [ ] Started end-to-end tests on the latest commit.

### Documentation updates
- [ ] Relevant Github READMEs updated **or** no GitHub README updates required.
- [ ] Relevant Wiki pages created/updated **or** no Wiki updates required.

### Optional
- [ ] Staging environment is unstaged before merging.
- [ ] Photo of a cute animal attached to this PR.

### CODE REVIEW

**Review by gerbeldo — APPROVED** [review]
👍

**Review by alexvpickering — CHANGES_REQUESTED** [review]
Can you please provide some context as to why these changes are necessary? 

If this is for making tests easier to run interactively,  do something like this instead https://github.com/hms-dbmi-cellenics/worker/pull/273

**Comment by alexvpickering** [comment]
> > Can you please provide some context as to why these changes are necessary?
> > If this is for making tests easier to run interactively, do something like this instead [hms-dbmi-cellenics/worker#273](https://github.com/hms-dbmi-cellenics/worker/pull/273)
> 
> But does `pkgload::load_all` load data in `data-raw/`? Docs say it loads things in `data/` only. I'm afk to test just now.

It doesn't load data in `data-raw` but it does load `sysdata.rda` which is where `gem2s` constants are (internal package data)

**Review by alexvpickering — APPROVED** [review]
Looks good, thanks m8! :dancers:

**Pull request merged**
